<?php

if (!defined('AppiEngine')) {
    header( "refresh:0; url=/");
}

$defaultAvatarList = [
    '404',
    'blagodarit',
    'eh',
    'grustit',
    'mechtaet',
    'ne-ponimaet',
    'ne-znaet',
    'odobrenie',
    'plachet',
    'pobeda',
    'pocelui',
    'podarok',
    'pomogite',
    'preduprezhdenie',
    'privet',
    'radost',
    'serdce',
    'skuchaet',
    'smeh',
    'spit',
    'spravka',
    'udivlenie',
    'ustal',
    'zadumalsya',
    'zloy',
];

$colors = [
    'red',
    'pink',
    'purple',
    'deep-purple',
    'indigo',
    'blue',
    'light-blue',
    'cyan',
    'teal',
    'green',
    'light-green',
    'lime',
    'yellow',
    'amber',
    'orange',
    'deep-orange',
    'brown',
    'blue-grey',
    'grey',
    'white',
    'black',
];

$modal = [
    'show' => false,
    'title' => '',
    'success' => 'none'
];

$monthN = [
    '01' => 'Января',
    '02' => 'Февраля',
    '03' => 'Марта',
    '04' => 'Апреля',
    '05' => 'Мая',
    '06' => 'Июня',
    '07' => 'Июля',
    '08' => 'Августа',
    '09' => 'Сентября',
    '10' => 'Октября',
    '11' => 'Ноября',
    '12' => 'Декабря'
];

$month = [
    '01' => 'Январь',
    '02' => 'Февраль',
    '03' => 'Март',
    '04' => 'Апрель',
    '05' => 'Май',
    '06' => 'Июнь',
    '07' => 'Июль',
    '08' => 'Август',
    '09' => 'Сентябрь',
    '10' => 'Октябрь',
    '11' => 'Ноябрь',
    '12' => 'Декабрь'
];

$apartmentTypes = [
    '1 Bedroom',
    '2 Bedrooms',
    '3 Bedrooms',
    '4+ Bedrooms',
    'Студия',
    'Комната',
];

$englishLevel = [
    'A1',
    'A2',
    'B1',
    'B2',
    'C1',
    'C2',
];

$otherCats = [
    "Транспорт",
    "&nbsp;&nbsp;Автомобили",
    "&nbsp;&nbsp;Мотоциклы и мототехника",
    "&nbsp;&nbsp;Грузовики и спецтехника",
    "&nbsp;&nbsp;Водный транспорт",
    "&nbsp;&nbsp;Запчасти и аксессуары",
    "Недвижимость",
    "&nbsp;&nbsp;Квартиры",
    "&nbsp;&nbsp;Комнаты",
    "&nbsp;&nbsp;Дома, дачи, коттеджи",
    "&nbsp;&nbsp;Земельные участки",
    "&nbsp;&nbsp;Гаражи и машиноместа",
    "&nbsp;&nbsp;Коммерческая недвижимость",
    "&nbsp;&nbsp;Недвижимость за рубежом",
    "Личные вещи",
    "&nbsp;&nbsp;Одежда, обувь, аксессуары",
    "&nbsp;&nbsp;Детская одежда и обувь",
    "&nbsp;&nbsp;Товары для детей и игрушки",
    "&nbsp;&nbsp;Красота и здоровье",
    "&nbsp;&nbsp;Часы и украшения",
    "Для дома и дачи",
    "&nbsp;&nbsp;Ремонт и строительство",
    "&nbsp;&nbsp;Мебель и интерьер",
    "&nbsp;&nbsp;Бытовая техника",
    "&nbsp;&nbsp;Продукты питания",
    "&nbsp;&nbsp;Растения",
    "&nbsp;&nbsp;Посуда и товары для кухни",
    "Запчасти и аксессуары",
    "&nbsp;&nbsp;Запчасти",
    "&nbsp;&nbsp;Шины, диски и колёса",
    "&nbsp;&nbsp;Аудио- и видеотехника",
    "&nbsp;&nbsp;Аксессуары",
    "&nbsp;&nbsp;Тюнинг",
    "&nbsp;&nbsp;Багажники и фаркопы",
    "&nbsp;&nbsp;Инструменты",
    "&nbsp;&nbsp;Прицепы",
    "&nbsp;&nbsp;Экипировка",
    "&nbsp;&nbsp;Масла и автохимия",
    "&nbsp;&nbsp;Противоугонные устройства",
    "&nbsp;&nbsp;GPS-навигаторы",
    "Электроника",
    "&nbsp;&nbsp;Телефоны",
    "&nbsp;&nbsp;Аудио и видео",
    "&nbsp;&nbsp;Товары для компьютера",
    "&nbsp;&nbsp;Игры, приставки и программы",
    "&nbsp;&nbsp;Ноутбуки",
    "&nbsp;&nbsp;Настольные компьютеры",
    "&nbsp;&nbsp;Фототехника",
    "&nbsp;&nbsp;Планшеты и электронные книги",
    "&nbsp;&nbsp;Оргтехника и расходники",
    "Хобби и отдых",
    "&nbsp;&nbsp;Билеты и путешествия",
    "&nbsp;&nbsp;Велосипеды",
    "&nbsp;&nbsp;Книги и журналы",
    "&nbsp;&nbsp;Коллекционирование",
    "&nbsp;&nbsp;Музыкальные инструменты",
    "&nbsp;&nbsp;Охота и рыбалка",
    "&nbsp;&nbsp;Спорт и отдых",
    "Животные",
    "&nbsp;&nbsp;Собаки",
    "&nbsp;&nbsp;Кошки",
    "&nbsp;&nbsp;Птицы",
    "&nbsp;&nbsp;Аквариум",
    "&nbsp;&nbsp;Другие животные",
    "&nbsp;&nbsp;Товары для животных",
    "Готовый бизнес и оборудование",
    "&nbsp;&nbsp;Готовый бизнес",
    "&nbsp;&nbsp;Оборудование для бизнеса",
    "Остальное",
];

$cities = [
    ["Удалёнка","США","Online","USA"],
    ["Абилин","Техас","Abilene","Texas"],
    ["Аврора","Колорадо","Aurora","Colorado"],
    ["Аврора","Иллинойс","Aurora","Illinois"],
    ["Акрон","Огайо","Akron","Ohio"],
    ["Александрия","Вирджиния","Alexandria","Virginia"],
    ["Аллентаун","Пенсильвания","Allentown","Pennsylvania"],
    ["Альбукерке","Нью-Мексико","Albuquerque","New Mexico"],
    ["Амарилло","Техас","Amarillo","Texas"],
    ["Анахайм","Калифорния","Anaheim","California"],
    ["Анкоридж","Аляска","Anchorage","Alaska"],
    ["Арвада","Колорадо","Arvada","Colorado"],
    ["Арлингтон","Техас","Arlington","Texas"],
    ["Арлингтон","Вирджиния","Arlington","Virginia"],
    ["Атенс","Джорджия","Athens","Georgia"],
    ["Атланта","Джорджия","Atlanta","Georgia"],
    ["Балтимор","Мэриленд","Baltimore","Maryland"],
    ["Батон-Руж","Луизиана","Baton Rouge","Louisiana"],
    ["Баффало","Нью-Йорк","Buffalo","New York"],
    ["Бейкерсфилд","Калифорния","Bakersfield","California"],
    ["Белвью","Вашингтон","Bellevue","Washington"],
    ["Бербанк","Калифорния","Burbank","California"],
    ["Беркли","Калифорния","Berkeley","California"],
    ["Биллингс","Монтана","Billings","Montana"],
    ["Бирмингем","Алабама","Birmingham","Alabama"],
    ["Бойсе","Айдахо","Boise","Idaho"],
    ["Бомонт","Техас","Beaumont","Texas"],
    ["Бостон","Массачусетс","Boston","Massachusetts"],
    ["Боулдер","Колорадо","Boulder","Colorado"],
    ["Браунсвилл","Техас","Brownsville","Texas"],
    ["Бриджпорт","Коннектикут","Bridgeport","Connecticut"],
    ["Валледжо","Калифорния","Vallejo","California"],
    ["Ванкувер","Вашингтон","Vancouver","Washington"],
    ["Вашингтон","Округ Колумбия","Washington","District of Columbia"],
    ["Вентура","Калифорния","San Buenaventura (Ventura)","California"],
    ["Вест-Вэлли-Сити","Юта","West Valley City","Utah"],
    ["Вест-Джордан","Юта","West Jordan","Utah"],
    ["Вест-Ковайна","Калифорния","West Covina","California"],
    ["Вестминстер","Колорадо","Westminster","Colorado"],
    ["Визалия","Калифорния","Visalia","California"],
    ["Викторвилл","Калифорния","Victorville","California"],
    ["Вирджиния-Бич","Вирджиния","Virginia Beach","Virginia"],
    ["Вустер","Массачусетс","Worcester","Massachusetts"],
    ["Гарден Грув","Калифорния","Garden Grove","California"],
    ["Гарлэнд","Техас","Garland","Texas"],
    ["Гейнсвилл","Флорида","Gainesville","Florida"],
    ["Гилберт","Аризона","Gilbert","Arizona"],
    ["Глендейл","Аризона","Glendale","Arizona"],
    ["Глендейл","Калифорния","Glendale","California"],
    ["Гранд Прейри","Техас","Grand Prairie","Texas"],
    ["Гранд-Рэпидс","Grand Rapids","Michigan"],
    ["Грешам","Орегон","Gresham","Oregon"],
    ["Грин Бэй","Висконсин","Green Bay","Wisconsin"],
    ["Гринсборо","Северная Каролина","Greensboro","North Carolina"],
    ["Давенпорт","Айова","Davenport","Iowa"],
    ["Даллас","Техас","Dallas","Texas"],
    ["Дарем","Северная Каролина","Durham","North Carolina"],
    ["Дауни","Калифорния","Downey","California"],
    ["Дейли-Сити","Калифорния","Daly City","California"],
    ["Дейтон","Огайо","Dayton","Ohio"],
    ["Де-Мойн","Айова","Des Moines","Iowa"],
    ["Денвер","Колорадо","Denver","Colorado"],
    ["Дентон","Техас","Denton","Texas"],
    ["Детройт","Мичиган","Detroit","Michigan"],
    ["Джексон","Миссисипи","Jackson","Mississippi"],
    ["Джерси-Сити","Нью-Джерси","Jersey City","New Jersey"],
    ["Джолит","Иллинойс","Joliet","Illinois"],
    ["Джэксонвилл","Флорида","Jacksonville","Florida"],
    ["Инглвуд","Калифорния","Inglewood","California"],
    ["Индепенденс","Миссури","Independence","Missouri"],
    ["Индианаполис","Индиана","Indianapolis","Indiana"],
    ["Ирвайн","Калифорния","Irvine","California"],
    ["Ирвинг","Техас","Irving","Texas"],
    ["Йонкерс","Нью-Йорк","Yonkers","New York"],
    ["Канзас-Сити","Канзас","Kansas City","Kansas"],
    ["Канзас-Сити","Миссури","Kansas City","Missouri"],
    ["Карроллтон","Техас","Carrollton","Texas"],
    ["Кейп Корал","Флорида","Cape Coral","Florida"],
    ["Киллин","Техас","Killeen","Texas"],
    ["Кларксвилл","Теннесси","Clarksville","Tennessee"],
    ["Кливленд","Огайо","Cleveland","Ohio"],
    ["Клирвотер","Флорида","Clearwater","Florida"],
    ["Коламбус","Огайо","Columbus","Ohio"],
    ["Коламбус","Джорджия","Columbus","Georgia"],
    ["Колорадо-Спрингс","Колорадо","Colorado Springs","Colorado"],
    ["Колумбия","Огайо","Columbia","South Carolina"],
    ["Колумбия","Миссури","Columbia","Missouri"],
    ["Конкорд","Калифорния","Concord","California"],
    ["Корал-Спрингс","Флорида","Coral Springs","Florida"],
    ["Корона","Калифорния","Corona","California"],
    ["Корпус-Кристи","Техас","Corpus Christi","Texas"],
    ["Коста Меса","Калифорния","Costa Mesa","California"],
    ["Кэмбридж","Массачусетс","Cambridge","Massachusetts"],
    ["Кэри","Северная Каролина","Cary","North Carolina"],
    ["Лаббок","Техас","Lubbock","Texas"],
    ["Ланкастер","Калифорния","Lancaster","California"],
    ["Лансинг","Мичиган","Lansing","Michigan"],
    ["Ларедо","Техас","Laredo","Texas"],
    ["Лас-Вегас","Невада","Las Vegas","Nevada"],
    ["Лафайетт","Луизиана","Lafayette","Louisiana"],
    ["Левисвилл","Техас","Lewisville","Texas"],
    ["Лексингтон","Кентукки","Lexington","Kentucky"],
    ["Линкольн","Небраска","Lincoln","Nebraska"],
    ["Литл-Рок","Арканзас","Little Rock","Arkansas"],
    ["Лонг-Бич","Калифорния","Long Beach","California"],
    ["Лос-Анджелес","Калифорния","Los Angeles","California"],
    ["Лоуэлл","Массачусетс","Lowell","Massachusetts"],
    ["Луисвилл","Кентукки","Louisville","Kentucky"],
    ["Лэйквуд","Колорадо","Lakewood","Colorado"],
    ["Майами","Флорида","Miami","Florida"],
    ["Майами Гарденс","Флорида","Miami Gardens","Florida"],
    ["Макаллен","Техас","McAllen","Texas"],
    ["Маккинни","Техас","McKinney","Texas"],
    ["Манчестер","Нью-Хэмпшир","Manchester","New Hampshire"],
    ["Мемфис","Теннесси","Memphis","Tennessee"],
    ["Мерфрисборо","Теннесси","Murfreesboro","Tennessee"],
    ["Меса","Аризона","Mesa","Arizona"],
    ["Мескит","Техас","Mesquite","Texas"],
    ["Мидленд","Техас","Midland","Texas"],
    ["Милуоки","Висконсин","Milwaukee","Wisconsin"],
    ["Миннеаполис","Миннесота","Minneapolis","Minnesota"],
    ["Мирамар","Флорида","Miramar","Florida"],
    ["Мобил","Алабама","Mobile","Alabama"],
    ["Модесто","Калифорния","Modesto","California"],
    ["Монтгомери","Алабама","Montgomery","Alabama"],
    ["Морено Вэлли","Калифорния","Moreno Valley","California"],
    ["Мэдисон","Висконсин","Madison","Wisconsin"],
    ["Напервилл","Иллинойс","Naperville","Illinois"],
    ["Новый Орлеан","Луизиана","New Orleans","Louisiana"],
    ["Ноксвилл","Теннесси","Knoxville","Tennessee"],
    ["Норман","Оклахома","Norman","Oklahoma"],
    ["Норуолк","Калифорния","Norwalk","California"],
    ["Норфолк","Вирджиния","Norfolk","Virginia"],
    ["Ньюарк","Нью-Джерси","Newark","New Jersey"],
    ["Нью-Йорк","Нью-Йорк","New York City","New York"],
    ["Ньюпорт-Ньюс","Вирджиния","Newport News","Virginia"],
    ["Нью-Хейвен","Коннектикут","New Haven","Connecticut"],
    ["Нэшвилл","Теннесси","Nashville","Tennessee"],
    ["Оверленд-Парк","Канзас","Overland Park","Kansas"],
    ["Огаста","Джорджия","Augusta","Georgia"],
    ["Одесса","Техас","Odessa","Texas"],
    ["Оклахома-Сити","Оклахома","Oklahoma City","Oklahoma"],
    ["Окленд","Калифорния","Oakland","California"],
    ["Окснард","Калифорния","Oxnard","California"],
    ["Олэйта","Канзас","Olathe","Kansas"],
    ["Омаха","Небраска","Omaha","Nebraska"],
    ["Онтарио","Калифорния","Ontario","California"],
    ["Ориндж","Калифорния","Orange","California"],
    ["Орландо","Флорида","Orlando","Florida"],
    ["Остин","Техас","Austin","Texas"],
    ["Оушенсайд","Калифорния","Oceanside","California"],
    ["Палм-Бэй","Флорида","Palm Bay","Florida"],
    ["Палмдейл","Калифорния","Palmdale","California"],
    ["Пасадена","Техас","Pasadena","Texas"],
    ["Пасадена","Калифорния","Pasadena","California"],
    ["Патерсон","Нью-Джерси","Paterson","New Jersey"],
    ["Пемброк-Пайнс","Флорида","Pembroke Pines","Florida"],
    ["Пеория","Аризона","Peoria","Arizona"],
    ["Пеория","Иллинойс","Peoria","Illinois"],
    ["Питтсбург","Пенсильвания","Pittsburgh","Pennsylvania"],
    ["Плано","Техас","Plano","Texas"],
    ["Помона","Калифорния","Pomona","California"],
    ["Помпано-Бич","Флорида","Pompano Beach","Florida"],
    ["Порт Сэнт Люси","Флорида","Port St. Lucie","Florida"],
    ["Портленд","Орегон","Portland","Oregon"],
    ["Провиденс","Род-Айленд","Providence","Rhode Island"],
    ["Прово","Юта","Provo","Utah"],
    ["Пуэбло","Колорадо","Pueblo","Colorado"],
    ["Ранчо Кукамонга","Калифорния","Rancho Cucamonga","California"],
    ["Раунд Рок","Техас","Round Rock","Texas"],
    ["Риверсайд","Калифорния","Riverside","California"],
    ["Рино","Невада","Reno","Nevada"],
    ["Ричардсон","Техас","Richardson","Texas"],
    ["Ричмонд","Калифорния","Richmond","California"],
    ["Ричмонд","Вирджиния","Richmond","Virginia"],
    ["Рокфорд","Иллинойс","Rockford","Illinois"],
    ["Роли","Северная Каролина","Raleigh","North Carolina"],
    ["Роузвилл","Калифорния","Roseville","California"],
    ["Рочестер","Нью-Йорк","Rochester","New York"],
    ["Рочестер","Миннесота","Rochester","Minnesota"],
    ["Саванна","Джорджия","Savannah","Georgia"],
    ["Сакраменто","Калифорния","Sacramento","California"],
    ["Салинас","Калифорния","Salinas","California"],
    ["Сан-Антонио","Техас","San Antonio","Texas"],
    ["Сан-Бернардино","Калифорния","San Bernardino","California"],
    ["Сан-Диего","Калифорния","San Diego","California"],
    ["Саннивейл","Калифорния","Sunnyvale","California"],
    ["Санта-Ана","Калифорния","Santa Ana","California"],
    ["Санта-Клара","Калифорния","Santa Clara","California"],
    ["Санта-Кларита","Калифорния","Santa Clarita","California"],
    ["Санта-Роза","Калифорния","Santa Rosa","California"],
    ["Сан-Франциско","Калифорния","San Francisco","California"],
    ["Сан-Хосе","Калифорния","San Jose","California"],
    ["Саут-Бенд","Индиана","South Bend","Indiana"],
    ["Северный Лас-Вегас","Невада","North Las Vegas","Nevada"],
    ["Сейлем","Орегон","Salem","Oregon"],
    ["Сентенниал","Колорадо","Centennial","Colorado"],
    ["Сент-Луис","Миссури","St. Louis","Missouri"],
    ["Сент-Питерсберг","Флорида","St. Petersburg","Florida"],
    ["Сент-Пол","Миннесота","St. Paul","Minnesota"],
    ["Сидар-Рапидс","Айова","Cedar Rapids","Iowa"],
    ["Сими Вэлли","Калифорния","Simi Valley","California"],
    ["Сиракьюс","Нью-Йорк","Syracuse","New York"],
    ["Сиэтл","Вашингтон","Seattle","Washington"],
    ["Скоттсдейл","Аризона","Scottsdale","Arizona"],
    ["Солт-Лейк-Сити","Юта","Salt Lake City","Utah"],
    ["Спокан","Вашингтон","Spokane","Washington"],
    ["Спрингфилд","Миссури","Springfield","Missouri"],
    ["Спрингфилд","Массачусетс","Springfield","Massachusetts"],
    ["Спрингфилд","Иллинойс","Springfield","Illinois"],
    ["Стерлинг Хайтс","Мичиган","Sterling Heights","Michigan"],
    ["Стоктон","Калифорния","Stockton","California"],
    ["Стэмфорд","Коннектикут","Stamford","Connecticut"],
    ["Су-Фолс","Южная Дакота","Sioux Falls","South Dakota"],
    ["Такома","Вашингтон","Tacoma","Washington"],
    ["Таллахасси","Флорида","Tallahassee","Florida"],
    ["Талса","Оклахома","Tulsa","Oklahoma"],
    ["Тампа","Флорида","Tampa","Florida"],
    ["Темпе","Аризона","Tempe","Arizona"],
    ["Толедо","Огайо","Toledo","Ohio"],
    ["Топика","Канзас","Topeka","Kansas"],
    ["Торнтон","Колорадо","Thornton","Colorado"],
    ["Торранс","Калифорния","Torrance","California"],
    ["Тусон","Аризона","Tucson","Arizona"],
    ["Уилмингтон","Северная Каролина","Wilmington","North Carolina"],
    ["Уинстон-Сейлем","Северная Каролина","Winston-Salem","North Carolina"],
    ["Уичита","Канзас","Wichita","Kansas"],
    ["Уичито-Фолс","Техас","Wichita Falls","Texas"],
    ["Уоррен","Мичиган","Warren","Michigan"],
    ["Уотербери","Коннектикут","Waterbury","Connecticut"],
    ["Уэйко","Техас","Waco","Texas"],
    ["Фаузенд-Оукс","Калифорния","Thousand Oaks","California"],
    ["Фейетвилл","Северная Каролина","Fayetteville","North Carolina"],
    ["Филадельфия","Пенсильвания","Philadelphia","Pennsylvania"],
    ["Финикс","Аризона","Phoenix","Arizona"],
    ["Флинт","Мичиган","Flint","Michigan"],
    ["Фонтана","Калифорния","Fontana","California"],
    ["Форт Коллинс","Колорадо","Fort Collins","Colorado"],
    ["Форт Уэйн","Индиана","Fort Wayne","Indiana"],
    ["Форт-Лодердейл","Флорида","Fort Lauderdale","Florida"],
    ["Форт-Уэрт","Техас","Fort Worth","Texas"],
    ["Фресно","Калифорния","Fresno","California"],
    ["Фримонт","Калифорния","Fremont","California"],
    ["Фриско","Техас","Frisco","Texas"],
    ["Фуллертон","Калифорния","Fullerton","California"],
    ["Фэрфилд","Калифорния","Fairfield","California"],
    ["Хай-Пойнт","Северная Каролина","High Point","North Carolina"],
    ["Хантингтон-Бич","Калифорния","Huntington Beach","California"],
    ["Хантсвилл","Алабама","Huntsville","Alabama"],
    ["Хартфорд","Коннектикут","Hartford","Connecticut"],
    ["Хендерсон","Невада","Henderson","Nevada"],
    ["Хиалеа","Флорида","Hialeah","Florida"],
    ["Холливуд","Флорида","Hollywood","Florida"],
    ["Хьюстон","Техас","Houston","Texas"],
    ["Хэйвард","Калифорния","Hayward","California"],
    ["Хэмптон","Вирджиния","Hampton","Virginia"],
    ["Цинциннати","Огайо","Cincinnati","Ohio"],
    ["Чандлер","Аризона","Chandler","Arizona"],
    ["Чарльстон","Южная Каролина","Charleston","South Carolina"],
    ["Чаттануга","Теннесси","Chattanooga","Tennessee"],
    ["Чесапик","Вирджиния","Chesapeake","Virginia"],
    ["Чикаго","Иллинойс","Chicago","Illinois"],
    ["Чула-Виста","Калифорния","Chula Vista","California"],
    ["Шарлотт","Северная Каролина","Charlotte","North Carolina"],
    ["Шривпорт","Луизиана","Shreveport","Louisiana"],
    ["Эвансвилл","Индиана","Evansville","Indiana"],
    ["Элгин","Иллинойс","Elgin","Illinois"],
    ["Элизабет","Нью-Джерси","Elizabeth","New Jersey"],
    ["Эль Монте","Калифорния","El Monte","California"],
    ["Эльк Грув","Калифорния","Elk Grove","California"],
    ["Эль-Пасо","Техас","El Paso","Texas"],
    ["Энн-Арбор","Мичиган","Ann Arbor","Michigan"],
    ["Эри","Пенсильвания","Erie","Pennsylvania"],
    ["Эскондидо","Калифорния","Escondido","California"],
    ["Юджин","Орегон","Eugene","Oregon"]
];